In [2]:
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.layers import Normalization,Dense,InputLayer
from tensorflow.keras.models import Sequential
import pydot
import graphviz

In [3]:
print(tf.__version__)
# !pip install --upgrade pydot

2.17.0


In [4]:
data = pd.read_csv('./Updated_data_car_price_prediction.csv')
data

Unnamed: 0                                car_name  car_prices_in_lakhs  \
0              0  Jeep Compass 2.0 Longitude Option BSIV                10.03   
1              1            Renault Duster RXZ Turbo CVT                12.83   
2              2                      Toyota Camry 2.5 G                16.40   
3              3                       Honda Jazz VX CVT                 7.77   
4              4        Volkswagen Polo 1.2 MPI Highline                 5.15   
...          ...                                     ...                  ...   
5507        5507                 BMW X1 sDrive 20d xLine                28.90   
5508        5508                   BMW M Series M4 Coupe                64.90   
5509        5509              Jaguar XF 2.2 Litre Luxury                13.75   
5510        5510                      BMW 7 Series 730Ld                29.90   
5511        5511               BMW 5 Series 520d M Sport                31.90   

      kms_driven  fuel_type  transmission  ownership  manufacture_year  \
0        86226.0          1             0          1              2017   
1        13248.0          2             1          1              2021   
2        60343.0          2             1          1              2016   
3        26696.0          2             1          1              2018   
4        69414.0          2             0          1              2016   
...          ...        ...           ...        ...               ...   
5507     45000.0          1             1          1              2018   
5508     29000.0          2             1          2              2015   
5509     90000.0          1             1          2              2013   
5510     79000.0          1             1          3              2015   
5511     42000.0          1             1          2              2017   

      engine_in_cc  seats  
0           1956.0      5  
1           1330.0      5  
2           2494.0      5  
3           1199.0      5  
4           1199.0      5  
...            ...    ...  
5507        2995.0      7  
5508        1968.0      5  
5509        2755.0      5  
5510        2967.0      6  
5511        1991.0      5  

[5512 rows x 10 columns]

In [5]:
data = data.iloc[:,2:]

In [6]:
data

car_prices_in_lakhs  kms_driven  fuel_type  transmission  ownership  \
0                   10.03     86226.0          1             0          1   
1                   12.83     13248.0          2             1          1   
2                   16.40     60343.0          2             1          1   
3                    7.77     26696.0          2             1          1   
4                    5.15     69414.0          2             0          1   
...                   ...         ...        ...           ...        ...   
5507                28.90     45000.0          1             1          1   
5508                64.90     29000.0          2             1          2   
5509                13.75     90000.0          1             1          2   
5510                29.90     79000.0          1             1          3   
5511                31.90     42000.0          1             1          2   

      manufacture_year  engine_in_cc  seats  
0                 2017        1956.0      5  
1                 2021        1330.0      5  
2                 2016        2494.0      5  
3                 2018        1199.0      5  
4                 2016        1199.0      5  
...                ...           ...    ...  
5507              2018        2995.0      7  
5508              2015        1968.0      5  
5509              2013        2755.0      5  
5510              2015        2967.0      6  
5511              2017        1991.0      5  

[5512 rows x 8 columns]

In [7]:
tensor_data = tf.constant(data)
tensor_data

<tf.Tensor: shape=(5512, 8), dtype=float64, numpy=
array([[1.0030e+01, 8.6226e+04, 1.0000e+00, ..., 2.0170e+03, 1.9560e+03,
        5.0000e+00],
       [1.2830e+01, 1.3248e+04, 2.0000e+00, ..., 2.0210e+03, 1.3300e+03,
        5.0000e+00],
       [1.6400e+01, 6.0343e+04, 2.0000e+00, ..., 2.0160e+03, 2.4940e+03,
        5.0000e+00],
       ...,
       [1.3750e+01, 9.0000e+04, 1.0000e+00, ..., 2.0130e+03, 2.7550e+03,
        5.0000e+00],
       [2.9900e+01, 7.9000e+04, 1.0000e+00, ..., 2.0150e+03, 2.9670e+03,
        6.0000e+00],
       [3.1900e+01, 4.2000e+04, 1.0000e+00, ..., 2.0170e+03, 1.9910e+03,
        5.0000e+00]])>

In [8]:
tensor_data = tf.random.shuffle(tensor_data)
tensor_data

<tf.Tensor: shape=(5512, 8), dtype=float64, numpy=
array([[4.3500e+00, 3.6000e+04, 2.0000e+00, ..., 2.0170e+03, 1.9680e+03,
        5.0000e+00],
       [1.7940e+01, 7.2558e+04, 1.0000e+00, ..., 2.0210e+03, 1.1930e+03,
        5.0000e+00],
       [6.1000e+01, 1.5000e+04, 2.0000e+00, ..., 2.0210e+03, 4.3670e+03,
        5.0000e+00],
       ...,
       [5.3300e+00, 3.3389e+04, 2.0000e+00, ..., 2.0150e+03, 1.3960e+03,
        5.0000e+00],
       [7.3500e+00, 9.1777e+04, 1.0000e+00, ..., 2.0160e+03, 1.2480e+03,
        5.0000e+00],
       [1.1000e+01, 6.3000e+04, 1.0000e+00, ..., 2.0170e+03, 4.4610e+03,
        5.0000e+00]])>

In [9]:
X = tensor_data[:,1:]
X

<tf.Tensor: shape=(5512, 7), dtype=float64, numpy=
array([[3.6000e+04, 2.0000e+00, 0.0000e+00, ..., 2.0170e+03, 1.9680e+03,
        5.0000e+00],
       [7.2558e+04, 1.0000e+00, 0.0000e+00, ..., 2.0210e+03, 1.1930e+03,
        5.0000e+00],
       [1.5000e+04, 2.0000e+00, 1.0000e+00, ..., 2.0210e+03, 4.3670e+03,
        5.0000e+00],
       ...,
       [3.3389e+04, 2.0000e+00, 0.0000e+00, ..., 2.0150e+03, 1.3960e+03,
        5.0000e+00],
       [9.1777e+04, 1.0000e+00, 1.0000e+00, ..., 2.0160e+03, 1.2480e+03,
        5.0000e+00],
       [6.3000e+04, 1.0000e+00, 1.0000e+00, ..., 2.0170e+03, 4.4610e+03,
        5.0000e+00]])>

In [10]:
y = tensor_data[:,0]
y = tf.expand_dims(y,axis=-1)
y

<tf.Tensor: shape=(5512, 1), dtype=float64, numpy=
array([[ 4.35],
       [17.94],
       [61.  ],
       ...,
       [ 5.33],
       [ 7.35],
       [11.  ]])>

In [11]:
normalizer = Normalization()

In [12]:
normalizer.adapt(X)

In [13]:
normalizer(X)

<tf.Tensor: shape=(5512, 7), dtype=float32, numpy=
array([[-0.6503745 ,  0.68794894, -0.6254731 , ...,  0.393224  ,
         0.75229913, -0.34822553],
       [ 0.22337568, -1.0117261 , -0.6254731 , ...,  1.411653  ,
        -0.58584964, -0.34822553],
       [-1.1522825 ,  0.68794894,  1.5987898 , ...,  1.411653  ,
         4.894517  , -0.34822553],
       ...,
       [-0.7127784 ,  0.68794894, -0.6254731 , ..., -0.11599051,
        -0.23534097, -0.34822553],
       [ 0.6827171 , -1.0117261 ,  1.5987898 , ...,  0.13861674,
        -0.4908842 , -0.34822553],
       [-0.00506417, -1.0117261 ,  1.5987898 , ...,  0.393224  ,
         5.0568213 , -0.34822553]], dtype=float32)>

In [14]:
model = Sequential()


In [15]:
model.add(InputLayer(shape=(7,)))
model.add(normalizer)
model.add(Dense(1))

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ normalization (Normalization)        │ (None, 7)                   │              15 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │               8 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 23 (96.00 B)

 Trainable params: 8 (32.00 B)

 Non-trainable params: 15 (64.00 B)

In [17]:
tf.keras.utils.plot_model(model,to_file='model.png',show_shapes=True)

AttributeError: module 'pydot' has no attribute 'InvocationException'

In [ ]:
print(pydot.__version__)
print(graphviz.__version__)